### ISSUE TITLE
plugin fails to load

### ISSUE THREAD

**Issue by maphouse** [davidvdev/obsidian-note-timer#5]
unable to enable plugin as instructed here https://github.com/davidvdev/obsidian-note-timer#installation

![image](https://user-images.githubusercontent.com/4475249/176110581-eb7be5cd-11b7-466c-bb81-1096eee93780.png)

**Comment by lisah2u** [comment]
Same issue.

**Comment by davidvdev** [comment]
It's been awhile since I've worked on this plugin, but I will take a look into it!

**Comment by davidvdev** [comment]
Verified this issue on my test vault.

The compressed folder did not contain a built version of `main.ts`, so the instructions have been updated for clarity on how to install.

**Comment by lisah2u** [comment]
That works. I instinctively grabbed the source zip first (before re-considering and grabbing the main.js) - and, of course, that didn't fix the issue given it was the same main.ts in the zip. Interesting plug-in!
